#%RAML 0.8
title: test
baseUri: http://test.com/{version}
version: v1

/auth:
  /o2:
    /token:
      get:
      post:
    
/profiles:
  get:
    queryParameters:
      size:
        type:  string
        
  post:
  /{user_id}:
    get:
/apps:
  get:
    description: Retrieve Appinfos
  post:
    description: Create new Appinfo
  /{app_id}:
    get:
      description: Retrieve the Appinfo
    post:
      description: Edit the Appinfo
    delete:
      description: Delete the Appinfo
    /reviews:
      get:
      post:
      /{review_id}:
        get:
        delete:
        post:
/boards:
  get:
  post:
  /{id}:
    get:
    post:
    delete:
    
    
