twitter:
    host: https://api.twitter.com
    auth_type: oauth1
    paths:
        auth_userinfo:
            path:  /1.1/account/verify_credentials.json
            response_map:
        userinfo: 
            path:  /1.1/
        search_tweets:
            path:   /1.1/search/tweets.json
            method: get
